# -*- coding: utf-8 -*-
"""tnbc full codes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZWY-zhKZgA8gylfq-rxmPpFlc9GydGLu
"""

# data extraction -  to get pdfs frm website
import json
import os
import requests
import pandas as pd
# Change the input_file_name if needed
input_file_name="Initial_TNBC_Pathology.xlsx"

df = pd.read_excel(input_file_name)

file_uuids = df['Pathology Report File UUID'].to_list()
def download_file(file_uuid, output_file_path):
    data_endpt = f"https://api.gdc.cancer.gov/data/{file_uuid}"

    try:
        response = requests.get(data_endpt, headers = {"Content-Type": "application/json"})

        with open(output_file_path, "wb") as output_file:
            output_file.write(response.content)

        print(f"File successfully downloaded.")

    except:
        print(f"Error!!!")
        return


if not os.path.exists(f"./Data/"):
    os.makedirs(f"./Data/")


for i in range(len(file_uuids)):
    if os.path.exists(f"./Data/{file_uuids[i]}.pdf"):
        print(f"File {file_uuids[i]}.tsv already exists in Data directory. Skipping download.")
        continue
    else:
        print(f"\nFetching data for file UUID: {file_uuids[i]}")
        download_file(file_uuids[i], f"./Data/{file_uuids[i]}.pdf")

# ocr extraction - to extract text frm eaach file

import os
from pdf2image import convert_from_path
import pytesseract
import pandas as pd

input_folder = "Data"
output_folder = "Modified_data"

os.makedirs(output_folder, exist_ok=True)
for filename in os.listdir(input_folder):
    if filename.lower().endswith(".pdf"):
        pdf_path = os.path.join(input_folder, filename)
        base_name = os.path.splitext(filename)[0]
        output_path = os.path.join(output_folder, base_name + ".xlsx")

        print(f"\nProcessing file: {filename}")
        try:
            images = convert_from_path(pdf_path, dpi=300)
        except Exception as e:
            print(f"Error converting {filename} to images: {e}")
            continue
        page_data = []
        for i, image in enumerate(images):
            text = pytesseract.image_to_string(image)
            page_data.append({
                "Page Number": i + 1,
                "Extracted Text": text.strip()
            })

        #Save to Excel
        df = pd.DataFrame(page_data)
        df.to_excel(output_path, index=False)
        print(f"Saved: {output_path}")

print("\nAll files processed and saved to Excel.")

# data got in previous step is formatted nd put in excel sheet with file name
import os
from pdf2image import convert_from_path
import pytesseract
import pandas as pd
from concurrent.futures import ProcessPoolExecutor

input_folder = "Data"
output_folder = "Modified_data"
os.makedirs(output_folder, exist_ok=True)

def process_pdf(filename):
    pdf_path = os.path.join(input_folder, filename)
    base_name = os.path.splitext(filename)[0]

    try:
        images = convert_from_path(pdf_path, dpi=300)
    except Exception as e:
        return {"File_name": base_name, "Extracted Text": f"Error: {e}"}

    full_text = ""
    for image in images:
        text = pytesseract.image_to_string(image)
        full_text += text.strip() + "\n"

    return {"File_name": base_name, "Extracted Text": full_text.strip()}
    return {"File_name": base_name, "ExtractedText": full_text.strip()}

if __name__ == "__main__":
    pdf_files = [f for f in os.listdir(input_folder) if f.lower().endswith(".pdf")]

    all_data = []
    count=0
    print("Processing PDF files ", end="")
    with ProcessPoolExecutor() as executor:
        for result in executor.map(process_pdf, pdf_files):
            count+=1
            all_data.append(result)
            if count==53 or count==len(pdf_files):
                print("█", end="")
                print(".", end="")
                count=0

    output_path = os.path.join(output_folder, "Modified_data.xlsx")
    output_path = "Modified_data.xlsx"
    df = pd.DataFrame(all_data)
    df.to_excel(output_path, index=False)

# feature extraction frm each report
import os
import json
import pandas as pd
import google.generativeai as genai
from openpyxl import Workbook, load_workbook

# --- Configuration ---
GOOGLE_API_KEY = "Enter your api key here"   # replace with your key
genai.configure(api_key=GOOGLE_API_KEY)

# Define input and output file names
input_excel_file = "Modified_data.xlsx"
output_excel_file = "features_gemini.xlsx"

# --- Excel Writing Function ---
def writeInSheets(file_name, tumor_size, er, pr, her2):
    """Writes the extracted features into an Excel spreadsheet."""
    if not os.path.exists(output_excel_file):
        wb = Workbook()
        ws = wb.active
        ws.title = "Features"
        headers = ["Source File Name", "Tumor Size", "ER", "PR", "HER2"]
        ws.append(headers)
        wb.save(output_excel_file)

    wb = load_workbook(output_excel_file)
    ws = wb.active
    ws.append([file_name, tumor_size, er, pr, her2])
    wb.save(output_excel_file)

# --- Gemini Extraction Function ---
def extract_features_with_gemini(report_context, model):
    """
    Extracts tumor size, ER, PR, HER2 from pathology report using JSON schema prompting.
    """
    prompt = f"""
    You are analyzing a pathology report.
    Extract the following features and normalize synonyms:

    - Tumor Size (in cm).
    - ER (Estrogen Receptor) status: "Positive" or "Negative".
        Synonyms: Estrogen receptor, ER receptor.
    - PR (Progesterone Receptor) status: "Positive" or "Negative".
        Synonyms: Progesterone receptor, PR receptor.
    - HER2/neu status: "Negative", "Positive", "1+", "2+", "3+".
        Synonyms: HER-2, HER2/neu, HER2 receptor, HER2 amplification.

    If not found, write "Not Reported".

    Provide the result in strict JSON format with keys:
    tumor_size, er, pr, her2.

    CONTEXT:
    {report_context}
    """
    try:
        response = model.generate_content(prompt)
        text_output = response.text.strip()

        # Try parsing JSON safely
        try:
            result = json.loads(text_output)
        except json.JSONDecodeError:
            # fallback if Gemini returns extra text
            text_output = text_output[text_output.find("{") : text_output.rfind("}")+1]
            result = json.loads(text_output)

        return (
            result.get("tumor_size", "Not Reported"),
            result.get("er", "Not Reported"),
            result.get("pr", "Not Reported"),
            result.get("her2", "Not Reported"),
        )

    except Exception as e:
        print(f"An error occurred while calling Gemini API: {e}")
        return ("Error", "Error", "Error", "Error")

# --- Main Execution ---
print("Initializing Gemini model...")
gemini_model = genai.GenerativeModel('gemini-2.5-flash-lite')

# Load input Excel
try:
    print(f"Reading data from {input_excel_file}...")
    df = pd.read_excel(input_excel_file)
except FileNotFoundError:
    print(f"Error: The input file '{input_excel_file}' was not found.")
    exit()

# Define expected columns
filename_column = 'File_name'
report_text_column = 'ExtractedText'

if report_text_column not in df.columns or filename_column not in df.columns:
    print(f"Error: Make sure your Excel file has columns named '{filename_column}' and '{report_text_column}'.")
    exit()

# Process rows
print(f"Found {len(df)} rows to process.")
for index, row in df.iterrows():
    file_name = row[filename_column]
    report_context = row[report_text_column]

    print(f"\n--- Processing Report: {file_name} (Row {index + 2}) ---")

    if not isinstance(report_context, str) or len(report_context) < 10:
        print("Skipping row due to empty or invalid report text.")
        writeInSheets(file_name, "Skipped", "Skipped", "Skipped", "Skipped")
        continue

    tumor_size, er, pr, her2 = extract_features_with_gemini(report_context, gemini_model)

    print(f"  Tumor Size: {tumor_size}")
    print(f"  ER Status: {er}")
    print(f"  PR Status: {pr}")
    print(f"  HER2 Status: {her2}")

    writeInSheets(file_name, tumor_size, er, pr, her2)

<<<<<<< HEAD
print(f"\n✅ Processing complete. All data written to {output_excel_file}")
=======
print(f"\n Processing complete. All data written to {output_excel_file}")
>>>>>>> 2c86134149a1c9dea64ecdd3016126a314c0df6c

# zero shot prompting with diff models
!pip install openai pandas openpyxl

import os
import json
import pandas as pd
from openpyxl import Workbook, load_workbook
from openai import OpenAI
from google.colab import files
from tqdm import tqdm

OPENAI_API_KEY ="Enter your api key here"
client = OpenAI(api_key=OPENAI_API_KEY)

input_excel_file = "Modified_data.xlsx"
output_excel_file = "features_openai.xlsx"

if not os.path.exists(input_excel_file):
    print(f"'{input_excel_file}' not found. Please upload it now")
    uploaded = files.upload()
    if input_excel_file not in uploaded:
        print(f"upload file named '{input_excel_file}'.")
        raise SystemExit
    print(f"Uploaded: {list(uploaded.keys())}")

def write_to_excel(file_name, tumor_size, er, pr, her2):
    """Appends extracted features into an Excel file."""
    if not os.path.exists(output_excel_file):
        wb = Workbook()
        ws = wb.active
        ws.title = "Features"
        headers = ["Source File Name", "Tumor Size", "ER", "PR", "HER2"]
        ws.append(headers)
        wb.save(output_excel_file)

    wb = load_workbook(output_excel_file)
    ws = wb.active
    ws.append([file_name, tumor_size, er, pr, her2])
    wb.save(output_excel_file)

def extract_features_openai(report_context):
    """
    Extracts tumor size, ER, PR, and HER2 from pathology text.
    Uses structured JSON output for reliability.
    """
    prompt = f"""
    You are analyzing a breast cancer pathology report.
    Extract the following fields (return valid JSON only):

    - tumor_size (in cm)
    - er ("Positive" or "Negative")
    - pr ("Positive" or "Negative")
    - her2 ("Negative", "Positive", "1+", "2+", or "3+")

    If any field is missing, use "Not Reported".
    Return only a valid JSON object with keys:
    tumor_size, er, pr, her2.

    CONTEXT:
    {report_context}
    """

    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
        )

        text_output = response.choices[0].message.content.strip()
        try:
            result = json.loads(text_output)
        except json.JSONDecodeError:
            text_output = text_output[text_output.find("{"): text_output.rfind("}")+1]
            result = json.loads(text_output)

        return (
            result.get("tumor_size", "Not Reported"),
            result.get("er", "Not Reported"),
            result.get("pr", "Not Reported"),
            result.get("her2", "Not Reported"),
        )

    except Exception as e:
        print(f"Error while calling OpenAI API: {e}")
        return ("Error", "Error", "Error", "Error")
print("Initializing extraction...")

try:
    df = pd.read_excel(input_excel_file)
except Exception as e:
    print(f"Error reading Excel file: {e}")
    raise SystemExit
filename_col = "File_name"
text_col = "text"

if filename_col not in df.columns or text_col not in df.columns:
    print(f"Missing columns. Ensure '{filename_col}' and '{text_col}' exist.")
    raise SystemExit

print(f"Found {len(df)} reports to process.\n")
for idx, row in tqdm(df.iterrows(), total=len(df), desc="Extracting features"):
    file_name = row[filename_col]
    report_context = row[text_col]

    if not isinstance(report_context, str) or len(report_context) < 10:
        write_to_excel(file_name, "Skipped", "Skipped", "Skipped", "Skipped")
        continue

    tumor_size, er, pr, her2 = extract_features_openai(report_context)
    write_to_excel(file_name, tumor_size, er, pr, her2)

print(f"\n Done! Results saved in: {output_excel_file}")

# one shot prompting with diff models
!pip install openai pandas openpyxl

import os
import json
import pandas as pd
from openpyxl import Workbook, load_workbook
from openai import OpenAI
from google.colab import files
from tqdm import tqdm

OPENAI_API_KEY ="Enter your api key here"
client = OpenAI(api_key=OPENAI_API_KEY)

input_excel_file = "Modified_data.xlsx"
output_excel_file = "features_openai.xlsx"

if not os.path.exists(input_excel_file):
    print(f"'{input_excel_file}' not found. Please upload it now")
    uploaded = files.upload()
    if input_excel_file not in uploaded:
        print(f"upload file named '{input_excel_file}'.")
        raise SystemExit
    print(f"Uploaded: {list(uploaded.keys())}")

def write_to_excel(file_name, tumor_size, er, pr, her2):
    """Appends extracted features into an Excel file."""
    if not os.path.exists(output_excel_file):
        wb = Workbook()
        ws = wb.active
        ws.title = "Features"
        headers = ["Source File Name", "Tumor Size", "ER", "PR", "HER2"]
        ws.append(headers)
        wb.save(output_excel_file)

    wb = load_workbook(output_excel_file)
    ws = wb.active
    ws.append([file_name, tumor_size, er, pr, her2])
    wb.save(output_excel_file)

def extract_features_openai(report_context):

    prompt = f"""
    You are a medical data extraction system.
    Do NOT reveal internal chain-of-thought.

    You will follow the ONE-SHOT example below and then extract data from the new report.

    ================= ONE-SHOT EXAMPLE =================
    INPUT REPORT:
    "Diagnosis: Invasive ductal carcinoma measuring 2.1 cm.
    ER: Positive (90%), PR: Negative (0%).
    HER2: 2+ (equivocal)."

    OUTPUT JSON:
    {{
      "tumor_size": "2.1 cm",
      "er": "Positive",
      "pr": "Negative",
      "her2": "2+"
    }}
    ====================================================

    Now process the NEW REPORT below and return JSON with:
    - tumor_size
    - er
    - pr
    - her2

    If a field is missing, output: "Not Reported".

    NEW REPORT:
    {report_context}
    """

    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
        )

        text_output = response.choices[0].message.content.strip()
        try:
            result = json.loads(text_output)
        except json.JSONDecodeError:
            text_output = text_output[text_output.find("{"): text_output.rfind("}")+1]
            result = json.loads(text_output)

        return (
            result.get("tumor_size", "Not Reported"),
            result.get("er", "Not Reported"),
            result.get("pr", "Not Reported"),
            result.get("her2", "Not Reported"),
        )

    except Exception as e:
        print(f"Error while calling OpenAI API: {e}")
        return ("Error", "Error", "Error", "Error")

print("Initializing extraction...")

try:
    df = pd.read_excel(input_excel_file)
except Exception as e:
    print(f"Error reading Excel file: {e}")
    raise SystemExit
filename_col = "File_name"
text_col = "text"

if filename_col not in df.columns or text_col not in df.columns:
    print(f"Missing columns. Ensure '{filename_col}' and '{text_col}' exist.")
    raise SystemExit

print(f"Found {len(df)} reports to process.\n")
for idx, row in tqdm(df.iterrows(), total=len(df), desc="Extracting features"):
    file_name = row[filename_col]
    report_context = row[text_col]

    if not isinstance(report_context, str) or len(report_context) < 10:
        write_to_excel(file_name, "Skipped", "Skipped", "Skipped", "Skipped")
        continue

    tumor_size, er, pr, her2 = extract_features_openai(report_context)
    write_to_excel(file_name, tumor_size, er, pr, her2)

print(f"\n Done! Results saved in: {output_excel_file}")

# few shot prompting with diff models
!pip install openai pandas openpyxl --quiet

import os
import json
import pandas as pd
from openpyxl import Workbook, load_workbook
from openai import OpenAI
from google.colab import files
from tqdm import tqdm

OPENAI_API_KEY = "Enter your api key here"
client = OpenAI(api_key=OPENAI_API_KEY)

input_excel_file = "Modified_data.xlsx"
output_excel_file = "features_openai.xlsx"

if not os.path.exists(input_excel_file):
    print(f"'{input_excel_file}' not found. Please upload it now.")
    uploaded = files.upload()
    if input_excel_file not in uploaded:
        print(f"Please upload a file named '{input_excel_file}'.")
        raise SystemExit
    print(f"Uploaded: {list(uploaded.keys())}")

def write_to_excel(file_name, tumor_size, er, pr, her2, ki67, p53):
    """Appends extracted features into an Excel file."""
    if not os.path.exists(output_excel_file):
        wb = Workbook()
        ws = wb.active
        ws.title = "Features"
        headers = ["Source File Name", "Tumor Size", "ER", "PR", "HER2", "Ki67", "p53"]
        ws.append(headers)
        wb.save(output_excel_file)

    wb = load_workbook(output_excel_file)
    ws = wb.active
    ws.append([file_name, tumor_size, er, pr, her2, ki67, p53])
    wb.save(output_excel_file)

def extract_features_openai(report_context):
    """
    Extracts HER2/neu, ER, PR, Ki-67, p53, and tumor size from a breast cancer pathology report.
    Returns structured JSON output with standardized labeling and reference-based classification.
    """

    prompt = f"""
    You are a medical data extraction system.
    Analyze the following breast cancer pathology reports and extract biomarker information.

    Extract and return the following fields as a valid JSON object:
    - tumor_size (in cm)
    - her2 ("Negative", "Equivocal", "Positive", "Ordered, result pending", or "Not Reported")
    - er ("Positive", "Negative", or "Not Reported")
    - pr ("Positive", "Negative", or "Not Reported")
    - ki67 (percentage + category: Low / Borderline / High / Not Reported)
    - p53 ("Positive", "Negative", or "Not Reported")

    Reference Ranges (for classification only, do not include in output):
    - ER/PR: Negative <1%, Positive ≥1%
    - Ki-67: Low <10%, Borderline 10–20%, High >20%
    - HER2/neu: Negative 0–1+, Equivocal 2+, Positive 3+ (reflexed to FISH if equivocal)

    Output Format Example:
    {{
        "tumor_size": "1.0 cm",
        "her2": "Negative (0–1+)",
        "er": "Positive (98%, 3+)",
        "pr": "Positive (95%, 3+)",
        "ki67": "12% (Borderline)",
        "p53": "Not Reported"
    }}

    If a field is not found in the report, explicitly return "Not Reported".

    EXAMPLE REPORTS FOR CONTEXT:
    Report 1:
    Breast, left, simple mastectomy: Invasive ductal carcinoma, Nottingham grade III (of III), is identified forming a 6.0 x 4.0 x 3.5 cm tumor (AJCC pT3) in the central-upper inner region of the breast.
    Her-2/NEU has been ordered on paraffin-embedded tissue on the left breast.

    Expected output:
    {{
        "tumor_size": "6.0 x 4.0 x 3.5 cm (left)",
        "her2": "Ordered, result pending",
        "er": "Not Reported",
        "pr": "Not Reported",
        "ki67": "Not Reported",
        "p53": "Not Reported"
    }}

    Report 2:
    IHC-stainings: Estrogen receptor - positive reaction 98% 3+; Progesterone receptor - positive reaction 95% 3+;
    Her-2/neu - negative reaction; Ki67 - 12%.

    Expected output:
    {{
        "tumor_size": "1.0 cm (left)",
        "her2": "Negative (0–1+)",
        "er": "Positive (98%, 3+)",
        "pr": "Positive (95%, 3+)",
        "ki67": "12% (Borderline)",
        "p53": "Not Reported"
    }}

    CONTEXT TO ANALYZE:
    {report_context}
    """

    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
        )

        text_output = response.choices[0].message.content.strip()

        try:
            result = json.loads(text_output)
        except json.JSONDecodeError:
            text_output = text_output[text_output.find("{"): text_output.rfind("}") + 1]
            result = json.loads(text_output)

        result = {
            "tumor_size": result.get("tumor_size", "Not Reported"),
            "her2": result.get("her2", "Not Reported"),
            "er": result.get("er", "Not Reported"),
            "pr": result.get("pr", "Not Reported"),
            "ki67": result.get("ki67", "Not Reported"),
            "p53": result.get("p53", "Not Reported"),
        }

        return result

    except Exception as e:
        print(f"Error while calling OpenAI API: {e}")
        return {
            "tumor_size": "Error",
            "her2": "Error",
            "er": "Error",
            "pr": "Error",
            "ki67": "Error",
            "p53": "Error",
        }

print("Initializing extraction...")

try:
    df = pd.read_excel(input_excel_file)
except Exception as e:
    print(f"Error reading Excel file: {e}")
    raise SystemExit

filename_col = "File_name"
text_col = "text"

if filename_col not in df.columns or text_col not in df.columns:
    print(f"Missing columns. Ensure '{filename_col}' and '{text_col}' exist.")
    raise SystemExit

print(f"Found {len(df)} reports to process.\n")

for idx, row in tqdm(df.iterrows(), total=len(df), desc="Extracting features"):
    file_name = row[filename_col]
    report_context = row[text_col]

    if not isinstance(report_context, str) or len(report_context) < 10:
        write_to_excel(file_name, "Skipped", "Skipped", "Skipped", "Skipped", "Skipped", "Skipped")
        continue

    result = extract_features_openai(report_context)
    write_to_excel(
        file_name,
        result["tumor_size"],
        result["er"],
        result["pr"],
        result["her2"],
        result["ki67"],
        result["p53"],
    )

print(f"\n Done! Results saved in: {output_excel_file}")

# chain of thought prompting with diff models
!pip install openai pandas openpyxl --quiet

import os
import json
import pandas as pd
from openpyxl import Workbook, load_workbook
from openai import OpenAI
from google.colab import files
from tqdm import tqdm

OPENAI_API_KEY = "Enter your api key here"
client = OpenAI(api_key=OPENAI_API_KEY)

input_excel_file = "Modified_data.xlsx"
output_excel_file = "features_openai.xlsx"

if not os.path.exists(input_excel_file):
    print(f"'{input_excel_file}' not found. Please upload it now.")
    uploaded = files.upload()
    if input_excel_file not in uploaded:
        print(f"Please upload a file named '{input_excel_file}'.")
        raise SystemExit
    print(f"Uploaded: {list(uploaded.keys())}")

def write_to_excel(file_name, tumor_size, er, pr, her2, ki67, p53):
    """Appends extracted features into an Excel file."""
    if not os.path.exists(output_excel_file):
        wb = Workbook()
        ws = wb.active
        ws.title = "Features"
        headers = ["Source File Name", "Tumor Size", "ER", "PR", "HER2", "Ki67", "p53"]
        ws.append(headers)
        wb.save(output_excel_file)

    wb = load_workbook(output_excel_file)
    ws = wb.active
    ws.append([file_name, tumor_size, er, pr, her2, ki67, p53])
    wb.save(output_excel_file)

def extract_features_openai(report_context, rag_context=""):
    """
    Uses a strict prompt that requests an external extraction_rationale (1-3 short bullets per biomarker).
    Returns a dict with keys:
      tumor_size, her2, er, pr, ki67, p53, extraction_rationale
    where extraction_rationale is itself a dict mapping biomarker -> list of short bullets.
    """

    prompt = f"""
You are a medical data extraction system. Do NOT reveal internal chain-of-thought or private model reasoning.
Instead, produce a concise, external step-by-step extraction log (1-3 short bullets per biomarker) called "extraction_rationale".

Task:
From the pathology report below, extract and return a JSON object with these keys:
- tumor_size (string; include units and laterality if present, or "Not Reported")
- her2 (one of: "Negative", "Equivocal", "Positive", "Ordered, result pending", or "Not Reported")
- er (one of: "Positive", "Negative", or "Not Reported"; if percent/score present include, e.g. "Positive (98%, 3+)")
- pr (same format as ER)
- ki67 (percentage + category: "12% (Borderline)" or "Not Reported")
- p53 (one of: "Positive", "Negative", "Not Reported")

Also include:
- extraction_rationale: a JSON object mapping each biomarker name to a short array of 1-3 succinct bullet strings that list the textual cues used to decide the value (e.g., ["ER: 'positive reaction 98% 3+' found", "Percent >=1% => Positive"]).

Reference rules for categorization (for model only; do not print these as part of rationale):
- ER/PR: Negative <1%, Positive ≥1%
- Ki-67: Low <10%, Borderline 10–20%, High >20%
- HER2: Negative 0–1+, Equivocal 2+, Positive 3+ (equivocal often reflexed to FISH)

If a field is not present in the report, set it to "Not Reported" and in rationale write a single bullet like "Not found".

Output format (strict JSON). Example:
{{
  "tumor_size": "6.0 x 4.0 x 3.5 cm (left)",
  "her2": "Ordered, result pending",
  "er": "Not Reported",
  "pr": "Not Reported",
  "ki67": "Not Reported",
  "p53": "Not Reported",
  "extraction_rationale": {{
      "tumor_size": ["Found 'forming a 6.0 x 4.0 x 3.5 cm tumor'"],
      "her2": ["Phrase 'Her-2/NEU has been ordered' -> Ordered, result pending"],
      "er": ["Not found"]
  }}
}}

RAG CONTEXT: {rag_context}

PATHOLOGY REPORT:
{report_context}

Return only valid JSON—no extra commentary.
"""

    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
        )

        text_output = response.choices[0].message.content.strip()

        # Try direct JSON parse first, else extract the first {...} block
        try:
            parsed = json.loads(text_output)
        except json.JSONDecodeError:
            # attempt to find JSON object in response
            start = text_output.find("{")
            end = text_output.rfind("}")
            if start != -1 and end != -1 and end > start:
                json_text = text_output[start:end+1]
                parsed = json.loads(json_text)
            else:
                raise

        # Ensure all top-level keys exist with defaults
        def ensure_field(d, key, default="Not Reported"):
            return d.get(key, default)

        tumor_size = ensure_field(parsed, "tumor_size", "Not Reported")
        her2 = ensure_field(parsed, "her2", "Not Reported")
        er = ensure_field(parsed, "er", "Not Reported")
        pr = ensure_field(parsed, "pr", "Not Reported")
        ki67 = ensure_field(parsed, "ki67", "Not Reported")
        p53 = ensure_field(parsed, "p53", "Not Reported")

        # extraction_rationale should be a dict of lists; provide safe defaults if missing
        raw_rationale = parsed.get("extraction_rationale", {})
        extraction_rationale = {}
        for key in ["tumor_size", "her2", "er", "pr", "ki67", "p53"]:
            val = raw_rationale.get(key)
            if isinstance(val, list) and all(isinstance(x, str) for x in val) and len(val) > 0:
                # keep as-is, but cap to 3 bullets
                extraction_rationale[key] = val[:3]
            else:
                # model didn't supply rationale for this key — follow your spec: single bullet "Not found" or mirror Not Reported
                if key in parsed and parsed[key] != "Not Reported":
                    extraction_rationale[key] = ["Found but no short rationale provided"]
                else:
                    extraction_rationale[key] = ["Not found"]

        result = {
            "tumor_size": tumor_size,
            "her2": her2,
            "er": er,
            "pr": pr,
            "ki67": ki67,
            "p53": p53,
            "extraction_rationale": extraction_rationale,
        }

        return result

    except Exception as e:
        # Keep the error format simple but structured so your pipeline can detect failures
        print(f"Error while calling OpenAI API: {e}")
        return {
            "tumor_size": "Error",
            "her2": "Error",
            "er": "Error",
            "pr": "Error",
            "ki67": "Error",
            "p53": "Error",
            "extraction_rationale": {
                "tumor_size": [f"Error: {e}"],
                "her2": [f"Error: {e}"],
                "er": [f"Error: {e}"],
                "pr": [f"Error: {e}"],
                "ki67": [f"Error: {e}"],
                "p53": [f"Error: {e}"],
            },
        }

print("Initializing extraction...")

try:
    df = pd.read_excel(input_excel_file)
except Exception as e:
    print(f"Error reading Excel file: {e}")
    raise SystemExit

filename_col = "File_name"
text_col = "text"

if filename_col not in df.columns or text_col not in df.columns:
    print(f"Missing columns. Ensure '{filename_col}' and '{text_col}' exist.")
    raise SystemExit

print(f"Found {len(df)} reports to process.\n")

for idx, row in tqdm(df.iterrows(), total=len(df), desc="Extracting features"):
    file_name = row[filename_col]
    report_context = row[text_col]

    if not isinstance(report_context, str) or len(report_context) < 10:
        write_to_excel(file_name, "Skipped", "Skipped", "Skipped", "Skipped", "Skipped", "Skipped")
        continue

    result = extract_features_openai(report_context)
    write_to_excel(
        file_name,
        result["tumor_size"],
        result["er"],
        result["pr"],
        result["her2"],
        result["ki67"],
        result["p53"],
    )

print(f"\n Done! Results saved in: {output_excel_file}")
